//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBNL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhongDat
    {
        public int MaPhong { get; set; }
        public int MaDonDatPhong { get; set; }
        public int GiaPhongDat { get; set; }
    
        public virtual DonDatPhong DonDatPhong { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
