//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBNL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatPhong()
        {
            this.ChiTietDichVuDats = new HashSet<ChiTietDichVuDat>();
            this.ChiTietPhongDats = new HashSet<ChiTietPhongDat>();
        }
    
        public int MaDonDatPhong { get; set; }
        public int MaKhach { get; set; }
        public string TinhTrangThanhToan { get; set; }
        public System.DateTime NgayDat { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<double> TongTien { get; set; }
        public int MaNhanVienThucHien { get; set; }
        public Nullable<int> MaNhanVienThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDichVuDat> ChiTietDichVuDats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhongDat> ChiTietPhongDats { get; set; }
        public virtual Khach Khach { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
