//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBNL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.ChiTietPhongDats = new HashSet<ChiTietPhongDat>();
        }
    
        public int MaPhong { get; set; }
        public int MaLoaiPhong { get; set; }
        public string TinhTrang { get; set; }
        public int Tang { get; set; }
        public int ThuTu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhongDat> ChiTietPhongDats { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
    }
}
